### ISSUE TITLE
`show` command does not work properly on certain websites

### ISSUE THREAD

**Issue by saidelike** [david-tejada/rango#118]
For instance on that website https://research.nccgroup.com/2022/02/18/analyzing-a-pjl-directory-traversal-vulnerability-exploiting-the-lexmark-mc3224i-printer-part-2/ and saying `show air near` we get:

![image](https://github.com/david-tejada/rango/assets/387346/6f7e35d1-dec7-4722-90db-071eada239be)

Most of the links on that site gives the same black window with nothing in it.

I confirmed on other sites that the command is working fine.

**Comment by david-tejada** [comment]
I see, it's because they have this stupid css rule using the universal selector:

```css
* {
  padding: 0px;
  margin: 0px;
  box-sizing: border-box;
  color: $black;
  font-family: $font;
  font-weight: 400;
  font-size: 19px;
  line-height: 1.75;
  -webkit-appearance: none;
}
```

I can fix this.

**Comment by david-tejada** [comment]
For reference, I need to add this second selector to this rule in _tippy.css_:

```css
.tippy-box,
.tippy-content div {
	position: relative;
	background-color: #333;
	color: #fff;
	border-radius: 4px;
	font-size: 14px;
	line-height: 1.4;
	white-space: normal;
	outline: 0;
	transition-property: transform, visibility, opacity;
	word-break: keep-all;
}
```
